// Generated Mon Jan 15 14:56:05 PST 2018

import Foundation

let ECODATUM_SCHEME = "http"
let ECODATUM_PORT = "8080"
let ECODATUM_HOST = "0.0.0.0"
let ECODATUM_BASE_URL = URL(string: "\(ECODATUM_SCHEME)://\(ECODATUM_HOST):\(ECODATUM_PORT)")!
let ECODATUM_BASE_API_URL = ECODATUM_BASE_URL.appendingPathComponent("api")
let ECODATUM_BASE_V1_API_URL = ECODATUM_BASE_API_URL.appendingPathComponent("v1")

let SWIFTY_BEAVER_APP_ID = "pgxJOG"
let SWIFTY_BEAVER_APP_SECRET = "u0ex2m3fhdmSdwzAwsxahqzZq91x2orE"
let SWIFTY_BEAVER_ENCRYPTION_KEY = "nruP7Yf0zgFhyzjv63wygYreZUsXln27"

let ECODATUM_DATABASE_FILE_NAME = "ecodatum.sqlite"

let DROP_AND_RECREATE_ECODATUM_DATABASE_FILE = true

